### PR TITLE
Adapt to SGr library release 2.0.0

### LINKED ISSUE #8: Update dependency versions for to 2.0.0 for commhandler and sgr-drivers
Prepare for the upcoming 2.0.0 of the libraries

### PR DESCRIPTION
**Pull request by mkrebs81**
merge after release has been published

### CODE REVIEW

**Comment by mkrebs81** [comment]
@ergo-furrer I have noticed a warning in the latest CI build:
```
warning: unknown enum constant XmlAccessType.FIELD
> Task :compileJava
  reason: class file for jakarta.xml.bind.annotation.XmlAccessType not found
warning: unknown enum constant XmlAccessType.FIELD
2 warnings
```

The warning goes away when I explicitly set the `jakarta.xml.bind-api` as dependency.
But this should not be necessary, as no "XML" classes are referenced in the code.
It also does not happen when I compile other applications such as the test lab integration.

Do you have an idea why this happens? Have we forgotten to add some dependencies to the `sgr-specification` package?
I tried some things on my local PC, but it did not change anything.

**Comment by ergo-furrer** [comment]
> @ergo-furrer I have noticed a warning in the latest CI build:
> 
> ```
> warning: unknown enum constant XmlAccessType.FIELD
> > Task :compileJava
>   reason: class file for jakarta.xml.bind.annotation.XmlAccessType not found
> warning: unknown enum constant XmlAccessType.FIELD
> 2 warnings
> ```
> 
> The warning goes away when I explicitly set the `jakarta.xml.bind-api` as dependency. But this should not be necessary, as no "XML" classes are referenced in the code. It also does not happen when I compile other applications such as the test lab integration.
> 
> Do you have an idea why this happens? Have we forgotten to add some dependencies to the `sgr-specification` package? I tried some things on my local PC, but it did not change anything. Why do i get the following warning even if XmlAccessType is not needed at compile time? warning: unknown enum constant XmlAccessType.FIELD
> Task :compileJava

The problem is that that 'jakarta.xml.bind-api'  is not in the compile time classpath, only in the runtime classpath. However the compiler uses indirectly JAXB annotations. ChatGPT 😉 :
``` If you're using a library that references JAXB annotations (like @XmlAccessorType), the compiler may expect XmlAccessType.FIELD to be present, even if you're not directly using that annotation in your code. This could trigger the warning during compilation.```

I think adding the dependency `jakarta.xml.bind-api' is the best solution to get rid of the warning.

**Comment by ergo-furrer** [comment]
@mkrebs81 I would like to change WagoSmartMeterCommunicator to use:
- SGrDeviceBuilder and DeviceInfo.readData() to read all datapoints

Can I do this on this branch?

**Comment by mkrebs81** [comment]
> @mkrebs81 I would like to change WagoSmartMeterCommunicator to use:
> 
>     * SGrDeviceBuilder and DeviceInfo.readData() to read all datapoints
> 
> 
> Can I do this on this branch?

Yes, you can. I do not need that branch any longer.

**Review by ergo-furrer — DISMISSED** [review]

**Comment by mkrebs81** [comment]
@ergo-furrer I published a release 2.0.1 which includes the most recent bugfixes but no interface changes.

**Review by ergo-furrer — APPROVED** [review]

**Pull request merged**
